#:schema node_modules/wrangler/config-schema.json
name = "astro-better-auth-d1"
pages_build_output_dir = "./dist"
compatibility_date = "2024-12-04"
compatibility_flags = ["nodejs_compat"]

[limits]
cpu_ms = 400

[[d1_databases]]
binding = "AUTH_DB"
database_name = "prod-auth"
# Update with your database id
database_id = "75c95b39-677a-4c44-8ea8-2ed9088eddce"

[[kv_namespaces]]
binding = "SESSIONS"
# Update with your namespace id
id = "35d69d5736ad497cb1bea479b807f962"