#:schema node_modules/wrangler/config-schema.json
name = "astro-cloudflare-better-auth-d1"
pages_build_output_dir = "./dist"
compatibility_date = "2024-12-04"

[limits]
cpu_ms = 400

[[d1_databases]]
binding = "DB"
database_name = "prod"
database_id = "d5757f62-76bc-47d4-ae61-c70ad3995985"
